dist: xenial

language: minimal

os:
- linux

sudo: required

env:
  global:
  - APPNAME="keycloak-configuration"
  - ORG="fairspace"
  - RELEASE_BRANCH="release"
  - SNAPSHOT_BRANCH="dev"
  - BUILD_SCRIPTS_REPO="fairspace/fairspace-build-scripts"
  - DOCKER_USERNAME="fairspace"
  - DEPLOYMENT_CONFIG_DIR="./config"
  - ACCOUNT_CONFIG_DIR="./config"
  - GCP_PROJECT="fairspace-207108"
  # DOCKER_PASSWORD = ...
  - secure: "NYvg29LIJ+8skSS2F+c7ZGaLyYW4MV90s45F48DfbAZAh3SfR8trTxIez9Zw49d0anB6QhrXyOgE1M+pdMSB962raiQRBy71zPfMnNFlrJKHqrbKPHrnlrlgwsDQ3hMPlM1jiLwhv/ssbYa7EgfWdOK9K+QSu75670dGRlbNDRroyde9Ig/pYubktTebrxvFoCAUhr4UxpvhwkoCejqAdY6veswVbjpNS5F9P4RADetRjQFF+ry1v7JaCBc+7L+RXOiNzWWEswU98Hez7yg8Jq/oJeGoUeTQwSiTCUx3NhJ8sP0QoscXVhU8j2+VftfE+f8/bMvbGGOkomW/srQls3DUL9wmhtIzo2Sjpuf5ZMRany90fWuOGTrWZnoYQmJh2xj7/OB/3bzsgsAE9Y3rnhDMvtA05wduuEzwHoRPnjtXGBhfLr8r6b25uao1Wr0wlrH0TBegkaEwQIqR5tLYnzLeKzwq4BA7QrI+OkP3A7NK8Q7eNd3jNSbUfa4t7ZF4Pv6tH30rII8F/8W+YE8Dwg1Lca/WgXsHs9RmN7cOGuDCqALxE2qvMCDuD9lANZAbeXM2S5yG9j5LJ8DuFM15zZB9IhOVVJkBgUmqKn8s+20IURaa3rhSoVGDqsvtcP+bODVhWwSho8xTw/7M1SiftjtfcoqiWaKKIwqc/Uo6HtU="
  - GITHUB_USERNAME="fairspace-ci"
  # GITHUB_PASSWORD = ...
  - secure: "pH0czZ4MIyfl9suIvJAvNe9+lujvd38YGg2/AcJmQIVOXsHAI5SGRAordPfHl3OgxS9Y9HJ7onETdPtEqQevBsXF4dmptq7bSGykLJXt1WP7wKsbXT7zpViDJQuQ3pT+f0wlj7O2vi7qZt664RK2pDArzdLZDJQZwhyQfPBrIveynKNM9F3I8Pe4qki9drEm0pb76KARhfQiQTeeemGub82MBj4lvxD6iQ13Lz4VS9bl4LbOo8mFz5Rd5a4i+fPHxrNzKq12bWGZQ9UPKonueXi0ZnYxSnPuJitFfE4B1eVsPgCmMN+SH8xSfY9nDLWQ3+zHgtPstu5SxZjzEdMgYLyRAd6bcMxWNYXmm2UI0IEzpdS9158Wpq7gP2wAXN6VeOPHQKoIH4VBBlPs52fky+e7o1ZTRV7B6OI5uc5ZAvvua7XxwdnXjfu4JOvYa/n6tcodUzL5bRs+jUP63CLMw2vbCCpIDigTLTqvxT5t1NJsZlQe4pjbBAkGnpESO1bdlPt0we8Z7ZfFp+1ZRNKhcsPEm9s50iGgQT4rMUTKD4wjM0uNkdCgztJTvFOKH9IYERGRd/UGodikB+b49Lp2WjbaMvr/7AI6yC544+6sFTLkk3VcIPpkilWf03dFUz1kdBuJIVM+LeaXbAdaLdoHc3/QKT4h2BbuElKG6w69ydg="

before_install:
- export KUBE_CONFIG_ENC_KEY=$encrypted_985abdf32880_key
- export KUBE_CONFIG_ENC_IV=$encrypted_985abdf32880_iv
- git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
- export BUILD_SCRIPTS_DIR=$(pwd)/ci
- 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export DEPLOY_PLATFORM="GCP" ; fi'
- 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_PLATFORM="GCP" ; fi'
- export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
- source ./ci/setup_env.sh

jobs:
  include:
  - stage: Check
    name: Check scripts for syntax errors and style issues
    install:
    - sudo apt-get install shellcheck
    script:
    - ./ci-syntax-check.sh
  - stage: Build
    name: Build and optionally push docker image
    services:
    - docker
    script:
    - ./ci/docker/build.sh
    - 'if [[ "$SHOULD_RELEASE" ]] ; then ./ci/login-provider.sh ; fi'
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/docker/release.sh; fi'
  - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - "./ci/versioning/add_tag_to_git.sh"
    - "./ci/versioning/set_next_version.sh"

notifications:
  slack:
    secure: "lljmvfbOtlGihwzfa0QOzU/TSCMC9HOM95fQEKBUXT/NuMAp9GPefEJHjAv/bivjVrpPtXqz1QFch+92V2XfNRblmg6FgKdxNt+J/EahPTPKkScQ3Y2tzbU+MCqykvu23U0WVb4euQFeEKG/yQuhvn1e3b7MvUrtkLshNwHjfUE8JS0UNybn178AaUkXcbTtPH9C5GzL16R9Lr1/5XX1kvde3ut7MSPnXAWh6om87yulmIhrV5WpfZroK/YKuGa5pGVSeiDwAaax6NhaJh7qry67wNtnbzi7DlkXvkh4SBc8SqKIfJ2tIqTYsw435PZ+kxeLK4PWmSYkoEWJ2RPvO9876bN42yn5GQXQ8FjHtGtEPWgtiUGXo+fmI/Z5hO72mvsLa+Frr+Yepop/1bJwGfZWzDt+wqkkQwzaUo63QNFOwt9GrROM62euQWwM6Ytrj8nnvddrqjlqdLCLrlmFkykj+5LOugx/Q+ucaQFEfpg0cDmeMU6iGrP20L9ovLz8tRlLJS5jwtko650U6yQtv//G7ym++ICYYekIoDUunPRw4MlEXVeZtozD2Kn30L+7j0xmLgcYg+qNct8lthm46IHjwCb2qJIp03Un5wING95tzWVO1eeZdSjIVBJpDzgCQvVDmqjO9kwx7DIZOeg2BcqLyULjWl1LCuouSYxus2Q="
