dist: xenial

language: minimal

os:
- linux

sudo: required

env:
  global:
  - APPNAME="keycloak-configuration"
  - ORG="fairspace"
  - RELEASE_BRANCH="master"
  - SNAPSHOT_BRANCH="dev"
  - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
  - DOCKER_USERNAME="fairspace"
  # DOCKER_PASSWORD = ...
  - secure: "NYvg29LIJ+8skSS2F+c7ZGaLyYW4MV90s45F48DfbAZAh3SfR8trTxIez9Zw49d0anB6QhrXyOgE1M+pdMSB962raiQRBy71zPfMnNFlrJKHqrbKPHrnlrlgwsDQ3hMPlM1jiLwhv/ssbYa7EgfWdOK9K+QSu75670dGRlbNDRroyde9Ig/pYubktTebrxvFoCAUhr4UxpvhwkoCejqAdY6veswVbjpNS5F9P4RADetRjQFF+ry1v7JaCBc+7L+RXOiNzWWEswU98Hez7yg8Jq/oJeGoUeTQwSiTCUx3NhJ8sP0QoscXVhU8j2+VftfE+f8/bMvbGGOkomW/srQls3DUL9wmhtIzo2Sjpuf5ZMRany90fWuOGTrWZnoYQmJh2xj7/OB/3bzsgsAE9Y3rnhDMvtA05wduuEzwHoRPnjtXGBhfLr8r6b25uao1Wr0wlrH0TBegkaEwQIqR5tLYnzLeKzwq4BA7QrI+OkP3A7NK8Q7eNd3jNSbUfa4t7ZF4Pv6tH30rII8F/8W+YE8Dwg1Lca/WgXsHs9RmN7cOGuDCqALxE2qvMCDuD9lANZAbeXM2S5yG9j5LJ8DuFM15zZB9IhOVVJkBgUmqKn8s+20IURaa3rhSoVGDqsvtcP+bODVhWwSho8xTw/7M1SiftjtfcoqiWaKKIwqc/Uo6HtU="
  - GITHUB_USERNAME="fairspace-ci"
  # GITHUB_PASSWORD = ...
  - secure: "FpHANX0VBMRC84WtJqjK+GUi6tJogcWCIFW3S+4MJxsxDRomvwT/Amfaauc8sc2Cy99R/Vs5uDpu59JXD/Og8EcEH9bjmkONNf/BvnSdMamcZONuf1E26N54vH9AT7KpSD0MS99hnZctGeQmLVfmAaz/6JmnJp0podeKvXHf8aBZ5plz2ieiEj38usojVwF02E0Y18qwH4oceoLUZFUnJdVXXLN1LM08/V72GFSFBTRPWy68btaquRY1pxXZk4cD1ijicerSV59DZhGKjNyifBX63Q9BjYveR0iTCBKvERD0nINLF7fWZhtPfYjHiskxgtI+MdoBrVKQSab3qsYFfTkzzlXYyXmZyHmVg7lJygfIkCH8gUJnsxv3GrGO0ScwBjDny41E++qDF+n5BPEw8lhJ9KDA5gN7Qzbt1WvkH22WsAo0yAtToMg+qQYYp+tbAz7/JNjZNK4ze6FgbQ9H3l6aPQ+TfTtyIL00lW5+FQ3DW0QlNHJZQqnaehP6NMMRsJ2xcgFPDNTPHD4Um62uevBVOfLxcO5H376IxXSpuKOW8XrnofileOJtElgEMms73TE1SaRSvZnheI85Z+XKLy3JqV1GhWrJXRvJPqC5j0rO4rAkqH79ZmikpB0YruBEiiHyCfS6BDIehrCzVKRH8Mmab0xZPSsay/xEU5q6UbA="

before_install:
- export KUBE_CONFIG_ENC_KEY=$encrypted_985abdf32880_key
- export KUBE_CONFIG_ENC_IV=$encrypted_985abdf32880_iv
- git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
- export BUILD_SCRIPTS_DIR=$(pwd)/ci
- 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export DEPLOY_PLATFORM="GCP" ; fi'
- 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_PLATFORM="AZURE" ; fi'
- export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
- source ./ci/setup_env.sh

jobs:
  include:
  - stage: Check
    name: Check scripts for syntax errors and style issues
    install:
    - sudo apt-get install shellcheck
    script:
    - ./ci-syntax-check.sh
  - stage: Build
    name: Build and optionally push docker image
    services:
    - docker
    script:
    - ./ci/docker/build.sh
    - 'if [[ "$SHOULD_RELEASE" ]] ; then ./ci/login-provider.sh ; fi'
    - 'if [[ $SHOULD_RELEASE ]]; then ./ci/docker/release.sh; fi'
  - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
    stage: Versioning
    name: Set tag and update version
    script:
    - "./ci/versioning/add_tag_to_git.sh"
    - "./ci/versioning/set_next_version.sh"

notifications:
  slack:
    secure: "lljmvfbOtlGihwzfa0QOzU/TSCMC9HOM95fQEKBUXT/NuMAp9GPefEJHjAv/bivjVrpPtXqz1QFch+92V2XfNRblmg6FgKdxNt+J/EahPTPKkScQ3Y2tzbU+MCqykvu23U0WVb4euQFeEKG/yQuhvn1e3b7MvUrtkLshNwHjfUE8JS0UNybn178AaUkXcbTtPH9C5GzL16R9Lr1/5XX1kvde3ut7MSPnXAWh6om87yulmIhrV5WpfZroK/YKuGa5pGVSeiDwAaax6NhaJh7qry67wNtnbzi7DlkXvkh4SBc8SqKIfJ2tIqTYsw435PZ+kxeLK4PWmSYkoEWJ2RPvO9876bN42yn5GQXQ8FjHtGtEPWgtiUGXo+fmI/Z5hO72mvsLa+Frr+Yepop/1bJwGfZWzDt+wqkkQwzaUo63QNFOwt9GrROM62euQWwM6Ytrj8nnvddrqjlqdLCLrlmFkykj+5LOugx/Q+ucaQFEfpg0cDmeMU6iGrP20L9ovLz8tRlLJS5jwtko650U6yQtv//G7ym++ICYYekIoDUunPRw4MlEXVeZtozD2Kn30L+7j0xmLgcYg+qNct8lthm46IHjwCb2qJIp03Un5wING95tzWVO1eeZdSjIVBJpDzgCQvVDmqjO9kwx7DIZOeg2BcqLyULjWl1LCuouSYxus2Q="
